export const interiorDesignFAQs = [
  // ── General ──
  { question: "What interior design services do you offer in NYC?", answer: "We offer 18 professional interior design services including full-home design, kitchen design, bathroom design, living room design, bedroom design, home office design, commercial interior design, space planning, color consultation, furniture selection, lighting design, custom closet design, renovation management, window treatment design, art curation, staging, wallpaper and wall treatments, and smart home integration.", category: "General" },
  { question: "Do you work in all five boroughs?", answer: "Yes. We provide full-service interior design across Manhattan, Brooklyn, Queens, the Bronx, and Staten Island, as well as Long Island, Westchester, and New Jersey. Each area has unique design challenges and we tailor our approach accordingly.", category: "General" },
  { question: "Are you licensed and insured?", answer: "Yes. We carry full general liability insurance, workers' compensation, and all required NYC business licenses. We coordinate DOB permits for renovation projects that require them and handle co-op and condo board alteration agreements.", category: "General" },
  { question: "How long have you been in business?", answer: "Our team has over 40 years of combined experience in interior design, architecture, and renovation management in New York City. We've completed over 2,500 projects across all property types from studio apartments to commercial offices.", category: "General" },
  { question: "Do you handle both residential and commercial projects?", answer: "Yes. We design residential interiors for apartments, condos, brownstones, townhouses, and houses, as well as commercial interiors for offices, retail spaces, restaurants, hotels, and medical offices. Same design excellence, different scale.", category: "General" },

  // ── Pricing ──
  { question: "How much does interior design cost in NYC?", answer: "Interior design costs in NYC vary based on project scope, property size, and material selections. A single-room design consultation starts around $2,500, while a full-home design for a 2-bedroom apartment ranges from $15,000 to $50,000+. Kitchen and bathroom renovations typically range from $25,000 to $100,000+ depending on finishes. Contact us for a free consultation tailored to your project.", category: "Pricing" },
  { question: "Do you charge for consultations?", answer: "No. We provide free initial consultations for all interior design projects in our service area. One of our designers will visit your property, discuss your vision, and provide a detailed proposal with no obligation.", category: "Pricing" },
  { question: "How do payments work?", answer: "Design-only projects follow a 50/50 structure — 50% at signing, 50% at design delivery. Full design-build projects follow a 30/40/30 structure — 30% deposit, 40% at midpoint, 30% on completion. Furniture procurement requires a 50% deposit with balance due before delivery. We're flexible on larger projects.", category: "Pricing" },
  { question: "Why does Manhattan cost more than other boroughs?", answer: "Access and logistics. Getting furniture and materials into Manhattan buildings requires freight elevator scheduling, building management coordination, DOT street permits for deliveries, and sometimes crane access for large items. The design quality is identical — the logistics add cost.", category: "Pricing" },
  { question: "Do you offer design packages?", answer: "Yes. We offer tiered design packages from e-design consultations to full-service design-build projects. Each package is customizable based on your needs, timeline, and budget. Contact us for details on our current packages and pricing.", category: "Pricing" },

  // ── Services ──
  { question: "Can you design a kitchen in a NYC apartment?", answer: "Absolutely — it's one of our specialties. We design custom kitchens that maximize every square inch, from galley kitchens in studios to chef-grade installations in brownstone renovations. We handle cabinetry, countertops, appliance specification, and coordinate with co-op boards and DOB permits.", category: "Services" },
  { question: "Do you handle renovation management?", answer: "Yes. NYC renovations are complex — co-op board approvals, DOB permits, contractor coordination, material lead times, building schedules. Our renovation management service handles every logistical detail so you can focus on the design.", category: "Services" },
  { question: "Can you help with real estate staging?", answer: "Yes. We provide professional staging for vacant and occupied properties. In NYC's competitive market, staging can significantly accelerate sales and maximize selling price. We handle furniture rental, styling, and photography coordination.", category: "Services" },
  { question: "Do you source furniture?", answer: "Yes. Our furniture selection service gives you access to trade-only showrooms, custom fabricators, and curated vintage dealers. We handle all procurement, delivery coordination with your building, and white-glove installation.", category: "Services" },
  { question: "Can you design a home office?", answer: "Yes. With remote work now permanent for many NYC professionals, we design home offices that boost productivity, look great on video calls, and integrate seamlessly into your home — whether you have a dedicated room or need to carve out a work zone.", category: "Services" },
  { question: "Do you do commercial interior design?", answer: "Yes. We design interiors for offices, retail stores, restaurants, hotels, medical offices, and co-working spaces throughout NYC. Our commercial team understands high-traffic demands and delivers designs that reinforce your brand while meeting ADA and building codes.", category: "Services" },

  // ── Process ──
  { question: "How does your design process work?", answer: "1) Free consultation at your property. 2) Design proposal within one week. 3) Concept development with mood boards and space plans. 4) Detailed design with specifications and 3D renderings. 5) Procurement and contractor coordination. 6) Installation and styling. Most residential projects complete in 8-16 weeks.", category: "Process" },
  { question: "How long does a typical project take?", answer: "A single-room design takes 4-8 weeks. Full-home design for an apartment takes 8-16 weeks. Kitchen or bathroom renovations take 12-20 weeks including construction. Staging can be completed in 1-2 weeks. Commercial projects vary based on scope.", category: "Process" },
  { question: "Do I need permits for interior renovation in NYC?", answer: "It depends on the scope. Cosmetic changes (paint, furniture, window treatments) don't require permits. Plumbing, electrical, and structural work require DOB permits. Co-op and condo renovations typically require board-approved alteration agreements. We handle all permitting and board coordination.", category: "Process" },
  { question: "Do you work with co-op and condo boards?", answer: "Yes. We work with building management and co-op/condo boards regularly. We prepare alteration agreement packages, coordinate with building architects and engineers, carry required insurance, and manage all building logistics including freight elevator scheduling and contractor access.", category: "Process" },
  { question: "Can I phase my project over time?", answer: "Absolutely. Many clients start with the most impactful rooms (kitchen, living room) and add bedrooms, bathrooms, and finishing touches over subsequent phases. We build phased plans that maintain design cohesion across the entire project timeline.", category: "Process" },

  // ── Specific Scenarios ──
  { question: "I have a small NYC apartment. Is professional design worth it?", answer: "Especially so. In small spaces, every decision matters more — the wrong sofa scale, poor layout, or missed storage opportunity is amplified. Our designers specialize in maximizing compact NYC apartments and can make a 500 sq ft studio feel dramatically larger and more functional.", category: "Specific Scenarios" },
  { question: "Can you work with my existing furniture?", answer: "Yes. We regularly design around pieces clients want to keep — whether it's a family heirloom, a favorite sofa, or art they love. We'll incorporate your existing pieces into a cohesive new design and recommend only what needs to be added or replaced.", category: "Specific Scenarios" },
  { question: "I'm renovating a brownstone. Can you handle the whole project?", answer: "Yes. Brownstone renovations are one of our specialties. We handle design for every floor, coordinate with architects and contractors, manage DOB permits, and oversee the entire renovation from demolition to final styling. We understand the unique character of NYC brownstones and how to honor original details while modernizing for today's living.", category: "Specific Scenarios" },
  { question: "Can you design for a new construction condo?", answer: "Yes. We work with buyers during the pre-construction phase to make design selections, customize finishes, and plan furniture layouts before closing. Starting design before move-in means you can walk into a finished home on day one.", category: "Specific Scenarios" },
  { question: "Do you work in Westchester, Long Island, and New Jersey?", answer: "Yes. We serve Westchester towns like Scarsdale, Bronxville, Rye, and Larchmont, Long Island including Garden City, Great Neck, Manhasset, and Huntington, and New Jersey waterfront communities like Hoboken, Jersey City, and Weehawken.", category: "Specific Scenarios" },
];
