export interface Job {
  title: string;
  slug: string;
  type: "FULL_TIME" | "PART_TIME" | "SEASONAL" | "CONTRACT";
  payType: "hourly" | "salary";
  payMin: number;
  payMax: number;
  payCurrency: string;
  payUnit: string;
  shortDesc: string;
  description: string;
  responsibilities: string[];
  qualifications: string[];
  benefits: string[];
  physical: string[];
  schedule: string;
  experience: string;
}

export const jobs: Job[] = [
  {
    title: "Interior Designer",
    slug: "interior-designer",
    type: "FULL_TIME",
    payType: "salary",
    payMin: 55000,
    payMax: 85000,
    payCurrency: "USD",
    payUnit: "YEAR",
    shortDesc: "Create custom interior designs for NYC residential and commercial properties from concept through installation.",
    description:
      "We are hiring an Interior Designer to join our design team. You will create custom interior design plans for residential and commercial properties across NYC, from Manhattan co-op apartments to Brooklyn brownstones to Westchester estates. This role combines creative vision with practical knowledge of NYC building requirements, vendor relationships, and project execution. You will work directly with clients from initial consultation through final styling, collaborating with contractors, architects, and our procurement team to deliver exceptional interiors.",
    responsibilities: [
      "Conduct on-site consultations, measure spaces, and assess client needs and lifestyle",
      "Develop design concepts including mood boards, color palettes, and material selections",
      "Create detailed floor plans, furniture layouts, and 3D renderings using design software",
      "Select and specify furniture, fixtures, finishes, fabrics, and accessories",
      "Prepare procurement lists, budgets, and project timelines",
      "Present designs to clients and incorporate feedback through revision cycles",
      "Coordinate with contractors, architects, and tradespeople during installation",
      "Manage multiple concurrent design projects across different stages",
      "Stay current on design trends, product launches, and NYC building regulations",
    ],
    qualifications: [
      "Bachelor's degree in Interior Design, Architecture, or related field",
      "3+ years of professional interior design experience",
      "Proficiency in AutoCAD, SketchUp, and/or rendering software (Enscape, Lumion)",
      "Strong knowledge of furniture, fabric, and finish sources and trade showrooms",
      "Understanding of NYC building codes, DOB permits, and co-op/condo board requirements",
      "Experience managing renovation projects in NYC apartments and townhouses",
      "Excellent client communication, presentation, and relationship skills",
      "Portfolio of completed residential and/or commercial projects",
      "Valid driver's license for site visits across the NYC metro area",
    ],
    benefits: [
      "Salary: $55,000-$85,000 based on experience and portfolio",
      "Health insurance contribution",
      "Paid time off and holidays",
      "Professional development budget for trade shows and certifications",
      "Design software licenses provided",
      "Trade showroom access and designer discounts",
      "Flexible schedule with remote design days",
      "Career growth into Lead Designer or Design Director",
    ],
    physical: [
      "Ability to visit job sites across the NYC metro area",
      "Walking, measuring, and surveying indoor spaces",
      "Occasional lifting of sample materials and presentation boards (under 25 lbs)",
    ],
    schedule: "Monday-Friday, 9:00 AM - 6:00 PM. Flexible remote days for design work. Occasional evening client meetings.",
    experience: "3+ years interior design experience. NYC project experience strongly preferred.",
  },
  {
    title: "Junior Interior Designer / Design Assistant",
    slug: "junior-interior-designer",
    type: "FULL_TIME",
    payType: "salary",
    payMin: 40000,
    payMax: 55000,
    payCurrency: "USD",
    payUnit: "YEAR",
    shortDesc: "Support senior designers with drafting, sourcing, sample management, and client coordination.",
    description:
      "We are looking for a motivated Junior Interior Designer or Design Assistant to support our senior design team. This is an ideal role for someone early in their interior design career who wants hands-on experience with real projects in New York City. You will assist with space planning, material research, sample management, vendor coordination, and presentation preparation. You will have the opportunity to take on increasing design responsibility as you develop your skills and client relationships.",
    responsibilities: [
      "Assist senior designers with floor plans, elevations, and design drawings",
      "Research and source furniture, fabrics, lighting, and materials per project specifications",
      "Manage material sample library — ordering, organizing, and returning samples",
      "Prepare mood boards, presentation decks, and client-facing documents",
      "Coordinate with vendors on pricing, lead times, and order status",
      "Attend site visits and take measurements, photographs, and field notes",
      "Track project budgets, purchase orders, and delivery schedules",
      "Assist with installation day styling, accessorizing, and photography",
      "Maintain project files, fabric binders, and digital asset libraries",
    ],
    qualifications: [
      "Bachelor's degree in Interior Design or related field (or currently completing)",
      "0-2 years of professional design experience (internships count)",
      "Proficiency in AutoCAD, SketchUp, or similar design software",
      "Strong working knowledge of Adobe Creative Suite (InDesign, Photoshop)",
      "Organized, detail-oriented, and able to manage multiple tasks simultaneously",
      "Familiarity with NYC design trade sources and showrooms",
      "Excellent written and verbal communication skills",
      "Reliable, punctual, and professional in client-facing situations",
      "Personal interest in interior design, architecture, and the NYC design scene",
    ],
    benefits: [
      "Salary: $40,000-$55,000 based on experience",
      "Health insurance contribution",
      "Paid time off and holidays",
      "Mentorship from senior designers",
      "Exposure to high-end residential and commercial projects",
      "Trade show and design event attendance",
      "Clear path to Interior Designer role within 1-2 years",
      "Design software licenses provided",
    ],
    physical: [
      "Ability to travel to job sites, showrooms, and vendor locations across NYC",
      "Carrying sample bags and material boards (up to 20 lbs)",
      "Standing for extended periods during installations and site visits",
    ],
    schedule: "Monday-Friday, 9:00 AM - 6:00 PM. Occasional weekend work during installations.",
    experience: "0-2 years. Recent graduates with strong portfolios and internship experience welcome.",
  },
  {
    title: "Project Manager",
    slug: "project-manager",
    type: "FULL_TIME",
    payType: "salary",
    payMin: 65000,
    payMax: 95000,
    payCurrency: "USD",
    payUnit: "YEAR",
    shortDesc: "Manage interior design and renovation projects from contract through completion across NYC properties.",
    description:
      "We are hiring a Project Manager to oversee the execution of interior design and renovation projects across the NYC metro area. You will be the bridge between our design team and the construction and installation teams, ensuring that every project is delivered on time, on budget, and to the design specification. NYC project management requires expertise in co-op and condo board processes, DOB permits, contractor coordination, and the logistical challenges of renovating in high-rise buildings. This role is ideal for someone with strong organizational skills, construction knowledge, and the ability to manage multiple stakeholders simultaneously.",
    responsibilities: [
      "Manage project timelines, budgets, and milestones from design handoff through completion",
      "Coordinate with contractors, electricians, plumbers, painters, and specialty tradespeople",
      "Oversee co-op and condo board alteration agreement processes",
      "Manage DOB permit applications and inspection scheduling",
      "Conduct regular site visits to monitor quality, progress, and safety",
      "Track and manage budgets, change orders, and payment schedules",
      "Coordinate furniture and material deliveries with building management",
      "Communicate project status to clients, designers, and company leadership",
      "Resolve on-site issues and make real-time decisions to keep projects on track",
      "Manage punch lists and final walkthroughs with clients",
    ],
    qualifications: [
      "3-5+ years of project management experience in interior design, construction, or renovation",
      "Deep knowledge of NYC renovation logistics — co-op/condo boards, DOB permits, building rules",
      "Experience managing budgets from $50,000 to $500,000+",
      "Strong understanding of construction sequences, trades, and building systems",
      "Proficiency in project management software (Asana, Monday.com, or similar)",
      "Exceptional organizational and communication skills",
      "Ability to manage 5-10 concurrent projects at different stages",
      "Problem-solving mindset — things go wrong on every project, and you fix them",
      "Valid driver's license for site visits across the NYC metro area",
      "Bachelor's degree preferred (Construction Management, Architecture, or related)",
    ],
    benefits: [
      "Salary: $65,000-$95,000 based on experience",
      "Health insurance",
      "Paid time off and holidays",
      "Company cell phone",
      "Mileage reimbursement for site visits",
      "Performance bonuses tied to on-time and on-budget delivery",
      "Professional development and certification support",
      "Career growth into Director of Operations",
    ],
    physical: [
      "Regular visits to active construction and renovation sites",
      "Climbing stairs in buildings without elevator access",
      "Walking and standing for extended periods during site inspections",
      "Occasional lifting of samples or materials (under 30 lbs)",
    ],
    schedule: "Monday-Friday, 8:00 AM - 6:00 PM. Flexibility required for site emergencies and deliveries.",
    experience: "3-5+ years project management in renovation, construction, or interior design. NYC experience required.",
  },
  {
    title: "3D Visualization Specialist",
    slug: "3d-visualization-specialist",
    type: "FULL_TIME",
    payType: "salary",
    payMin: 50000,
    payMax: 75000,
    payCurrency: "USD",
    payUnit: "YEAR",
    shortDesc: "Create photorealistic 3D renderings and virtual walkthroughs for interior design projects.",
    description:
      "We are hiring a 3D Visualization Specialist to produce photorealistic renderings, animations, and virtual walkthroughs for our interior design projects. Our clients expect to see their spaces before any work begins, and your renderings are the key tool that sells our designs and secures client approval. You will work closely with our design team to translate 2D plans and mood boards into stunning 3D visuals that accurately represent materials, lighting, proportions, and atmosphere. This role is ideal for someone who combines technical 3D modeling skills with a strong eye for interior design aesthetics.",
    responsibilities: [
      "Create photorealistic 3D renderings of residential and commercial interior designs",
      "Build detailed 3D models from floor plans, elevations, and design specifications",
      "Apply accurate materials, textures, and lighting to match specified finishes",
      "Produce virtual walkthroughs and 360-degree views for client presentations",
      "Collaborate with designers to interpret concepts and translate them into 3D",
      "Maintain a library of 3D models for commonly specified furniture and fixtures",
      "Revise renderings based on client and designer feedback",
      "Ensure rendering quality meets portfolio and marketing standards",
    ],
    qualifications: [
      "2+ years of professional 3D visualization experience",
      "Expert proficiency in 3ds Max, SketchUp, or Revit",
      "Expert proficiency in rendering engines: V-Ray, Enscape, Lumion, or Corona",
      "Strong understanding of interior design principles, materials, and lighting",
      "Ability to accurately model and texture real-world materials (wood, marble, fabric, metal)",
      "Experience with post-processing in Photoshop",
      "Portfolio demonstrating photorealistic interior renderings",
      "Strong attention to detail — scale, proportions, and material accuracy matter",
      "Bachelor's degree in Architecture, Interior Design, or Digital Media preferred",
    ],
    benefits: [
      "Salary: $50,000-$75,000 based on experience and portfolio quality",
      "Health insurance contribution",
      "Paid time off and holidays",
      "High-performance workstation and dual monitors provided",
      "Software licenses provided (3ds Max, V-Ray, Adobe Suite)",
      "Remote work flexibility — most rendering work can be done from home",
      "Exposure to high-end residential and commercial projects",
      "Portfolio development opportunities with published project photography",
    ],
    physical: [
      "Primarily desk-based work at a computer workstation",
      "Occasional site visits for reference photography and measurements",
    ],
    schedule: "Monday-Friday, 9:00 AM - 6:00 PM. Flexible remote schedule. Occasional deadline-driven extended hours.",
    experience: "2+ years 3D visualization experience. Interior design or architecture firm experience preferred.",
  },
  {
    title: "Furniture Installer / Delivery Coordinator",
    slug: "furniture-installer",
    type: "FULL_TIME",
    payType: "hourly",
    payMin: 20,
    payMax: 30,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Coordinate and execute furniture deliveries, assembly, and installation for interior design projects across NYC.",
    description:
      "We are hiring a Furniture Installer and Delivery Coordinator to handle the final and most critical phase of our interior design projects — getting everything into the space, assembled, placed, and styled. NYC furniture delivery is uniquely challenging: narrow staircases, freight elevator schedules, building delivery windows, tight doorways, and walk-up apartments all require careful planning and execution. You will coordinate deliveries from multiple vendors, manage building access logistics, assemble furniture, and work with our design team to place every piece according to the design plan.",
    responsibilities: [
      "Coordinate furniture and accessory deliveries from multiple vendors and warehouses",
      "Schedule and manage building freight elevator and loading dock access",
      "Receive, inspect, and inventory all delivered items against purchase orders",
      "Assemble furniture, mount artwork, install window treatments, and arrange accessories",
      "Place furniture and decor according to designer floor plans and specifications",
      "Handle white-glove delivery — protecting floors, walls, and elevators during moves",
      "Manage returns, exchanges, and damage claims for defective items",
      "Maintain organized inventory of items in transit and in storage",
    ],
    qualifications: [
      "2+ years of furniture delivery, installation, or moving experience",
      "Experience navigating NYC building delivery logistics (freight elevators, COIs, super coordination)",
      "Ability to assemble furniture from various manufacturers (IKEA to custom pieces)",
      "Basic tool proficiency (drills, levels, anchors, picture hanging hardware)",
      "Valid driver's license and clean driving record",
      "Ability to drive box trucks and cargo vans in NYC traffic",
      "Strong organizational skills for managing multi-vendor delivery schedules",
      "Professional demeanor — you will be in clients' homes",
      "English proficiency required; Spanish bilingual a plus",
    ],
    benefits: [
      "Competitive hourly pay: $20-$30/hr based on experience",
      "Consistent year-round work",
      "Company vehicle provided for delivery routes",
      "Tools and equipment provided",
      "Overtime opportunities during busy installation weeks",
      "Tips from residential clients",
      "Path to Lead Installer or Warehouse Manager",
    ],
    physical: [
      "Lifting and carrying furniture up to 75+ lbs regularly",
      "Navigating narrow staircases and walk-up buildings with large items",
      "Standing, bending, and kneeling for extended periods during assembly",
      "Working in occupied and unoccupied residential spaces",
    ],
    schedule: "Monday-Friday, 7:00 AM - 4:00 PM. Occasional Saturdays for installation days.",
    experience: "2+ years furniture delivery or installation experience. NYC building logistics experience preferred.",
  },
  {
    title: "Staging Specialist",
    slug: "staging-specialist",
    type: "FULL_TIME",
    payType: "hourly",
    payMin: 22,
    payMax: 35,
    payCurrency: "USD",
    payUnit: "HOUR",
    shortDesc: "Stage NYC apartments and homes for real estate listings using rented furnishings and styling expertise.",
    description:
      "We are hiring a Staging Specialist to prepare NYC apartments, townhouses, and condos for real estate sales and rentals. You will work with our design team to transform empty or lived-in properties into aspirational, market-ready spaces that photograph beautifully and appeal to buyers. This role combines logistics, styling skill, and speed — staging projects often need to be completed in one to two days. You will coordinate furniture rentals, manage delivery schedules, style every room, and ensure the property is photo-ready. Both full-time and contract positions are available.",
    responsibilities: [
      "Stage vacant and occupied properties using rented and owned furnishings",
      "Style rooms with furniture, art, textiles, books, plants, and accessories for maximum visual impact",
      "Coordinate furniture rental orders, delivery, and pickup with staging inventory companies",
      "Work with real estate photographers to ensure spaces are styled for optimal photography",
      "Manage staging inventory — track items, schedule pickups, handle returns",
      "Conduct property walkthroughs and develop staging plans with the design team",
      "De-stage properties after sale or listing period ends",
      "Maintain staging supplies (linens, accessories, styling props) in organized condition",
    ],
    qualifications: [
      "2+ years of home staging, visual merchandising, or interior styling experience",
      "Strong eye for composition, color, and spatial arrangement",
      "Knowledge of current design trends and buyer preferences in the NYC real estate market",
      "Ability to work quickly and efficiently under tight deadlines",
      "Experience working with staging furniture rental companies",
      "Physically able to move and arrange furniture, hang art, and style for extended hours",
      "Valid driver's license and ability to transport styling supplies",
      "Portfolio or photos demonstrating staging work",
      "Professional demeanor for interacting with real estate agents and property owners",
    ],
    benefits: [
      "Competitive hourly pay: $22-$35/hr based on experience",
      "Consistent work — NYC real estate staging is year-round",
      "Company vehicle or mileage reimbursement for site travel",
      "Styling supply budget",
      "Portfolio development with professional photography of staged properties",
      "Flexible scheduling — full-time and contract positions available",
      "Networking with NYC real estate professionals",
      "Path to Lead Stager or Staging Director",
    ],
    physical: [
      "Moving and arranging furniture (with team support for heavy items)",
      "Carrying staging supplies and accessories (up to 30 lbs)",
      "Standing and working on feet for 6-10 hours during staging days",
      "Working in walk-up buildings and buildings without freight elevators",
    ],
    schedule: "Monday-Friday with occasional weekends for staging deadlines. Hours vary by project — typical staging days run 8:00 AM - 5:00 PM.",
    experience: "2+ years staging, visual merchandising, or interior styling. NYC real estate experience preferred.",
  },
];

export function findJobBySlug(slug: string): Job | undefined {
  return jobs.find((j) => j.slug === slug);
}

export function getAllJobSlugs(): string[] {
  return jobs.map((j) => j.slug);
}
